freeCodeCamp/mobile

- lib/ui/views/browser/browser_view.dart
- lib/ui/widgets/drawer_widget/drawer_widget_view.dart
Checklist:
- [x ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x ] My pull request has a descriptive title (not a vague title like `Update index.md`)
Displays gets cut if the phone is having a notch or is having a punch hole camera on menu screen & WebView screen. Issue fixed with SafeArea Widget.
> Fixed SafeArea issue on Drawer & WebView Screen, Issue in mobiles having notch or Punch hole camera

- lib/ui/views/news/news-feed/news_feed_view.dart
there seems to be a build in truncate function for text.
> fix: truncate news title if over two lines

- sample.env
the news key is save for everyone to use as stated in the Ghost API:
Content API keys are provided via a query parameter in the url. These keys are safe for use in browsers and other insecure environments, as they only ever provide access to public data. Sites in private mode should consider where they share any keys they create.
> fix: update sample env with news key

- mobile-app/lib/ui/views/home/home_view.dart
Checklist:
Having the `views` and `titles` variables inside the `build()` method is a side effect and causes unnecessary variable calls.
I have moved the views and titles variables outside the `build()` method, and made them static const.
I have warped the `views` Widgets inside the `IndexedStack` Widget which caches the children widgets state and prevents loading Widget in every time the BottomNavigationBar changes.
> moved variables outside build() method

- mobile-app/lib/ui/views/news/news-feed/news_feed_viewmodel.dart
- mobile-app/pubspec.lock
- mobile-app/pubspec.yaml
Checklist:
Closes #182 
This project was failing to build on Flutter 2.8 . On following the dependency tree, the following solution worked
- flutter_html - ^2.1.2 to ^2.2.1
- flutter_svg - ^0.22.0 to ^0.23.0+1
flutter svg has a more latest version available but it is not supported by flutter_html for now.
Also in `news_feed_viewmodel.dart` there was an import missing because of which the build was failing. I have added the `import 'dart:developer' as dev` .
> feat: Updated dependencies for successful build on Flutter 2.8 

- renovate.json
Uses the global config (automated updates received ~~and merged~~ on weekends 🎉, dashboard issue, less noise overall).
If confident about merges (usually means good tests / linting), let me know to include the approval bots in the config and we can enable skipping approvals by humans. Else this can go in as-is regardless for the weekend-ly updates.
> chore(renovate): use common global config

- mobile-app/pubspec.lock
This removes some of the noisy warnings when developing apps. 
Only one package(flutter_math_fork which is used by flutter_html) still hasn't updated their code to fix the warnings.
> chore(app): update lockfile

- mobile-app/integration_test/news_test.dart
- mobile-app/lib/ui/views/news/news-article/news_article_viewmodel.dart
The extra `pumpAndSettle` in the test is to change the view and then wait for the "bookmark" button to appear.
> fix(tests): scroll controller error in app test

- .github/workflows/flutter-ci.yml
- .github/workflows/flutter-deploy.yml
Flutter 3 seems stable now and we've been using it for local development. So I updated the actions to use Flutter 3.0.x
> chore: update flutter version in actions

- mobile-app/lib/service/authentication_service.dart
- mobile-app/lib/ui/widgets/drawer_widget/drawer_widget_view.dart
- mobile-app/lib/ui/widgets/login_webview_widget/login_webview_view.dart
When I was making the log in flow I had set it up in such a way that the `WebView` cookies would be persisted so this allow the user to login faster after their first login(by fetching the same cookies used in the previous successful login). But I didn't think of the case wherein a different user might want to login in the same device. This PR fixes that situation.
Thanks to @ojeytonwilliams for pointing this out.
> fix: log in flow

- mobile-app/lib/ui/widgets/podcast_widgets/podcast_progressbar_widget.dart
Checklist:
Closes #451
Screenshot of the changed code is attached below:
**Problems:** 
- Basically in the previous code the ball only moves after 42 seconds.
-  The ending of the podcast and the progress bar was not in sync (either the bar stops early, or there is still left of the podcast)
**Solution:** 
- By dividing with larger number the seconds will be reduced. I have made it to 14 seconds.
- Calculated the amount of newWidth and multiplied with 0.95
> fix: updated the UI of the progress bar in podcast

- .github/workflows/deploy-api.yml
- package.json
I've created a build command for the API at the root `package.json`.
@raisedadead is there any other command you need to be created at the root `package.json`?
> chore(api): create api commands at root level

- mobile-app/lib/ui/widgets/tag_widget.dart
The article tags wil now truncate if they are to big.
When holding the article tag a tooltip will show up with the full article tag name. 
This pr prevent tags to go on more than 2 lines or having an inconsistent height.
> fix: article tags

- mobile-app/analysis_options.yaml
This makes it easier to find path errors in the `app.dart` file when adding or renaming routes.
> fix: make app file debugable

- mobile-api/Dockerfile
Renovate upgraded the node docker image from 16 to 19 and 19 is not the latest LTS version. This PR downgrades it v18 which is the latest LTS version of Node.
Checklist:
Closes #XXXXX
> chore(api): downgrade node image to LTS version

- mobile-app/lib/ui/views/news/html_handler/html_handler.dart
> fix: codeblock rendering

- .github/workflows/deploy-api.yml
Swapping the Azure Container Registry with DigitalOcean Container Registry for the low-deployment.
Note that while it is not evident in the PR, the API deployments will also move from Azure Container Instances to DigitalOcean's Apps - deploying the instances from DOCR, with automatic deployments when the image is updated via this GitHub Action.
> feat(actions): use DOCR registry instead of ACR

- mobile-app/lib/ui/views/news/html_handler/html_handler.dart
Checklist:
Closes #XXXXX
I think this may fix the text selection errors also by using `SelectionArea` the buttons displayed are native one of the system.
> fix: selection errors

- mobile-app/lib/models/news/tutorial_model.dart
- mobile-app/lib/ui/views/news/news-feed/news_feed_view.dart
- mobile-app/lib/ui/views/news/news-tutorial/news_tutorial_view.dart
- mobile-app/lib/ui/widgets/tutorial_list_widget.dart
Checklist:
Closes #XXXXX
This [article](https://www.freecodecamp.org/news/want-to-learn-typescript-heres-our-free-22-part-course-21cd9bbb5ef5/) doesn't have a banner image and so it wouldn't load and crash the app.
Crashlytics report - https://console.firebase.google.com/u/1/project/mobile-4ee8a/crashlytics/app/android:org.freecodecamp/issues/c9ec186d68409cc16db6181d93623416?time=last-thirty-days&sessionEventKey=651D016E03210004107F391115692116_1864426950094230251
> fix: display default banner for articles without banner image

- codemagic.yaml
Checklist:
Closes #XXXXX
Looking at the hotfix changelog, flutter version 3.13.7 could prevent the recent increase in build time outs in codemagic.
> fix: codemagic failing build

- mobile-app/lib/service/authentication/authentication_service.dart
Checklist:
Closes #XXXXX
Login error dialogs were not awaited and some crashlytics report seem to say the response schema is different from what we get from the API.
Crashlytics report:
* https://console.firebase.google.com/u/1/project/mobile-4ee8a/crashlytics/app/ios:org.freecodecamp.ios/issues/ac7c7e9f9e7891b0009ed5d6e8df478d?time=last-seven-days&sessionEventKey=6436e301d7ad4fd7bfe1b3e0d4f2803a_1879083395981658281
* https://console.firebase.google.com/u/1/project/mobile-4ee8a/crashlytics/app/android:org.freecodecamp/issues/57fb110671c5bcc8135b4ce6506068e9?time=last-seven-days&sessionEventKey=65523025010A00010917AEB0ACB74BC8_1879396829724126472
I've not used the localisation strings here as I'm hoping with this PR the number of failed logins will reduce. If it goes well then in a future …
> fix: OAuth login issues

- mobile-app/lib/service/authentication/authentication_service.dart
- mobile-app/lib/ui/views/news/html_handler/html_handler.dart
- mobile-app/lib/ui/views/podcast/podcast-list/podcast_list_view.dart
- mobile-app/lib/ui/views/settings/delete-account/delete_account_viewmodel.dart
- mobile-app/lib/ui/views/settings/settings_view.dart
- mobile-app/lib/ui/widgets/drawer_widget/drawer_widget_viewmodel.dart
- mobile-app/lib/ui/widgets/podcast_widgets/podcast_tilte_widget.dart
Route names are supposed to be like sub-paths. These'll be used in the future with dynamic links
Checklist:
Closes #XXXXX
> fix: route names

- mobile-app/lib/service/learn/learn_offline_service.dart
Checklist:
Closes #XXXXX
I've commented out the code which was "caching" challenge data so that when we come back to offline service we can discuss more about it.
> fix: stop showing cached challenge data

- mobile-app/lib/ui/views/learn/test_runner.dart
Seems like UNPKG started linking Chai.js to a new major version. https://www.npmjs.com/package/chai?activeTab=versions v5 seems to be pretty new and not compatible with our test runner. 
We should probably link to specific version for Mocha too.
closes #1165
> fix: chai.js pointing to new major version

- mobile-app/lib/ui/widgets/podcast_widgets/podcast_tilte_widget.dart
Checklist:
Removed HTML widget because of maxLines property did not work as expected if the content contains elements like line breaks or other block-level elements that can break the line. That's why I added the text widget, by parsing the body of the description used as textcontent in the widget. By using the text widget we can see max lines 3
Closes #1175
> fix: podcast episode preview content

- .github/workflows/flutter-ci.yml
- .github/workflows/flutter-deploy.yml
- .github/workflows/mobile-curriculum-e2e.yml
- codemagic.yaml
- mobile-app/ios/Podfile.lock
- mobile-app/lib/enums/theme_type.dart
- mobile-app/lib/service/authentication/authentication_service.dart
- mobile-app/lib/ui/theme/fcc_theme.dart
- mobile-app/lib/ui/views/learn/challenge/challenge_view.dart
- mobile-app/lib/ui/views/learn/challenge/templates/python-project/python_project_view.dart
- mobile-app/lib/ui/views/learn/challenge/templates/python/python_view.dart
- mobile-app/lib/ui/views/learn/landing/landing_view.dart
- mobile-app/lib/ui/views/learn/widgets/dynamic_panel/panels/hint/hint_widget_view.dart
- mobile-app/lib/ui/views/learn/widgets/dynamic_panel/panels/pass/pass_widget_view.dart
- mobile-app/lib/ui/views/news/news-search/news_search_view.dart
- mobile-app/lib/ui/views/podcast/episode-list/episode_list_view.dart
- mobile-app/lib/ui/views/settings/delete-account/delete_account_view.dart
- mobile-app/lib/ui/views/settings/delete-account/delete_account_viewmodel.dart
- mobile-app/lib/ui/widgets/drawer_widget/drawer_widget_view.dart
- mobile-app/lib/ui/widgets/setup_dialog_ui.dart
- mobile-app/pubspec.lock
- mobile-app/pubspec.yaml
> feat: flutter 3.16

- mobile-app/lib/models/learn/challenge_model.dart
- mobile-app/lib/ui/views/learn/block/block_view.dart
- mobile-app/lib/ui/views/learn/challenge/challenge_view.dart
- mobile-app/lib/ui/views/learn/challenge/challenge_viewmodel.dart
- mobile-app/lib/ui/views/learn/challenge/templates/odin/odin_view.dart
- mobile-app/lib/ui/views/learn/challenge/templates/odin/odin_viewmodel.dart
- mobile-app/lib/ui/views/news/html_handler/html_handler.dart
> feat: The Odin Project superblock

- mobile-app/ios/Podfile.lock
- mobile-app/lib/service/firebase/analytics_observer.dart
- mobile-app/lib/service/podcast/notification_service.dart
- mobile-app/lib/ui/views/learn/landing/landing_view.dart
- mobile-app/lib/ui/widgets/drawer_widget/drawer_widget_view.dart
- mobile-app/pubspec.lock
- mobile-app/pubspec.yaml
Checklist:
Updating the packages first so that it becomes easier to migrate to Gradle 8 and Flutter 3.19 along with replacing older unmaintained packages.
Packages to replace
> chore: upgrade flutter packages

- mobile-app/pubspec.lock
- mobile-app/pubspec.yaml
- mobile-app/test_driver/integration_test.dart
Checklist:
The CI test was failing for android devices because in PR #1225 I had bumped the android version to API 33(Android 13) to be in line with the target version present in the android config files. In Android 13, the notification permission dialog was introduced and since the tests were not updated to handle it, they were all waiting for a response thereby leading to the action to never end & overtime at 6 hrs.
Thanks to the folks who solved this bounty(https://github.com/FilledStacks/acceptpermission_bounty/pull/1) I could get this to work locally. Now to test it in the CI 🤞
> fix: ci grant permission

- mobile-app/lib/enums/ext_type.dart
Checklist:
I believe this is the cause of the below Crashlytics report.
Crashlytics reports
- https://console.firebase.google.com/u/1/project/mobile-4ee8a/crashlytics/app/ios:org.freecodecamp.ios/issues/83caeef22555e1af692689e727621047
- https://console.firebase.google.com/u/1/project/mobile-4ee8a/crashlytics/app/android:org.freecodecamp/issues/34fde8f1fe309bbdbf007344afa9a696
> fix: return type of parseExt from api data

- .github/workflows/mobile-curriculum-e2e.yml
- mobile-app/lib/service/learn/learn_file_service.dart
- mobile-app/lib/service/learn/learn_service.dart
- mobile-app/lib/ui/views/learn/test_runner.dart
- mobile-app/test/widget_test.dart
> fix: odin project tests

- mobile-app/.gitignore
- mobile-app/lib/ui/views/learn/challenge/templates/multiple_choice/multiple_choice_view.dart
- mobile-app/lib/ui/views/learn/challenge/templates/python/python_view.dart
1. Fixed full screen issue for youtube videos played in tutorials - this is done by adding a callback for fullscreen listener as specified in the library documentation ([example app](https://github.com/sarbagyastha/youtube_player_flutter/blob/aecc29691cfa6828e48547515f80737df7cd82aa/packages/youtube_player_iframe/example/lib/pages/video_list_page.dart#L42))
3. Added gitignore file inside the `mobile-app` directory and added fvm related files for developers who use fvm
Checklist:
- [x ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)
Closes #1306
**Additional …
> fix: full screen issue for youtube videos played in tutorials

- mobile-app/lib/ui/views/news/news-image-viewer/news_image_view.dart
Checklist:
-  [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
-  [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) 
Closes #1315
- The PR is created to improve to the functioinality of the news image viewer button on iOS
- I added a back button to the page to navigate back to the tutorial page
> fix: add back button to news tutorial image viewer

- mobile-app/lib/ui/views/learn/challenge/challenge_view.dart
- mobile-app/lib/ui/views/learn/challenge/challenge_viewmodel.dart
- mobile-app/pubspec.lock
- mobile-app/pubspec.yaml
> feat: symbol bar

- mobile-app/lib/models/learn/challenge_model.dart
- mobile-app/lib/service/audio/audio_service.dart
- mobile-app/lib/ui/views/learn/challenge/templates/english/english_view.dart
- mobile-app/lib/ui/views/learn/widgets/audio/audio_player_view.dart
Checklist:
@Nirajn2311 , please take a look at this video it will help the both of us: https://www.youtube.com/watch?v=xvFZjo5PgG0
> fix: handle nullable timestamps in audio model and service

- .github/workflows/mobile-curriculum-e2e.yml
- .gitignore
- e2e/learn.spec.js
- e2e/playwright.config.js
- package-lock.json
- package.json
Checklist:
The rationale is that these tests are of the mobile app, not the learn client. As such it makes more sense for them to be in this repo.
It's a little ugly, though, since we still need to import curriculum data from the main repo.
I converted the spec and test back to js since it did not seem worth configuring TS for two files. At least not right now.
> chore: move playwright tests from main repo

- e2e/learn.spec.js
- mobile-app/lib/ui/views/learn/test_runner.dart
> chore: update curriculum helpers to latest versions in test runner

- mobile-app/lib/ui/views/learn/challenge/challenge_view.dart
- mobile-app/lib/ui/views/learn/widgets/dynamic_panel/panels/pass/pass_widget_view.dart
Checklist:
I'm setting the background color of the complete challenge button to `green40` to improve the contrast ratio between the text and the background.
Here is the value of `green40`: (https://github.com/freeCodeCamp/ui/blob/e541d9e25d604e93ca3e6ff6399d30645d7bc3a1/src/colors.css#L39).
<details>
| --- | --- |
| ![Simulator Screenshot - iPhone Xʀ - 2025-03-26 at 15 19 15](https://github.com/user-attachments/assets/496c0fd2-5291-4d37-9b0e-87633a5a5c0c) | ![Simulator Screenshot - iPhone Xʀ - 2025-03-26 at 14 58 28](https://github.com/user-attachments/assets/63e6c87c-1ac9-4615-97b1-4640b86c099d) |
</details>
> fix(a11y): improve contrast ratio of complete button

- mobile-app/ios/Podfile.lock
- mobile-app/lib/service/podcast/notification_service.dart
Checklist:
Closes #XXXXX
Should hopefully fix this issue: https://console.firebase.google.com/u/1/project/mobile-4ee8a/crashlytics/app/android:org.freecodecamp/issues/c58e4e6ccdc6385ec7464bf3086b9cec?time=last-seven-days&types=crash&sessionEventKey=67B8339000F400012B7FB8141713DCCA_2052225893469884727
> fix: dont ask permissions before notification initialization

- mobile-app/integration_test/news/bookmark_test.dart
Reverts freeCodeCamp/mobile#1377
The PR doesn't fix the test as PRs from forked repos won't get access to secrets in the actions for security reasons and so the CI actions will fail. Yes, this is a known problem and should be fixed with mocking of api responses
> Revert "fix: bookmark test"

- .github/workflows/mobile-curriculum-e2e.yml
- e2e/learn.spec.js
Rather than installing the freeCodeCamp repo at root and then putting mobile in a sub-dir, the workflow puts them in sibling folders. That makes it easier to work with locally, since you can work on the repos independently.
Checklist:
> refactor: move repos in CI so it's easier to test locally

- mobile-app/lib/ui/views/news/html_handler/html_handler.dart
Checklist:
Changes link text color from blue to white, to improve readability and a11y. We also use white for link text in the web version, so this change is also to align with that.
<details>
| --- | --- |
| ![Simulator Screenshot - iPhone Xʀ - 2025-04-16 at 16 11 28](https://github.com/user-attachments/assets/13725ccc-128e-4ec7-a8cd-694490e99c53) | ![Simulator Screenshot - iPhone Xʀ - 2025-04-16 at 16 10 51](https://github.com/user-attachments/assets/bcc4ecfc-2c69-4a8b-882a-72a22abb4fb3) |
</details>
> fix: link text color

- mobile-app/lib/service/learn/learn_file_service.dart
- mobile-app/lib/ui/views/learn/challenge/challenge_view.dart
- mobile-app/lib/ui/views/learn/challenge/challenge_viewmodel.dart
> fix: Syntax highlighting and incorrect file display on multi-editor challenges

- mobile-app/lib/service/learn/learn_service.dart
Checklist:
v2 is now live so I'm just creating PRs targeting `main` instead of a feature branch.
This PR:
- Uses curriculum data v2 for `submit-types.json`
- There is no differences in the file content, we just moved the file under `/curriculum-data/v2` now, rather than leaving it in the `/curriculum-data` root. This apparently is a bug in v1, we expect the file to be under `/curriculum-data/v1`, but this isn't flagged by the test because the test case is missing an assertion (`expect()`): https://github.com/freeCodeCamp/freeCodeCamp/blob/181321d90dffd8ed2e27fd76eebd5dbc013b9730/tools/scripts/build/build-external-curricula-data-v1.test.ts#L41-L45
- Is related to #1426
> chore(service): use v2 submit-types.json

- mobile-app/lib/ui/views/learn/challenge/templates/english/english_view.dart
- mobile-app/lib/ui/views/learn/challenge/templates/multiple_choice/multiple_choice_view.dart
- mobile-app/lib/ui/views/learn/widgets/explanation_widget.dart
Checklist:
This PR:
- Moves the explanation implementation to a shared widget.
- Displays the explanation widget on fill in the blanks challenges. (This is a follow-up to #1462. We only added explanation to multiple-choice question challenges in that PR because I forgot that `explanation` is also available in fill in the blanks challenges.)
<details>
| Multiple-choice question | Fill in the blanks |
| --- | --- |
| <img width="409" alt="Screenshot 2025-05-08 at 18 13 24" src="https://github.com/user-attachments/assets/3dcc9bc5-410d-45fc-9c54-ebc7cded4417" /> | <img width="413" alt="Screenshot 2025-05-08 at 18 13 39" src="https://github.com/user-attachments/assets/deea05bd-924a-4244-ae15-392484c4db04" /> |
</details>
> feat(view): add explanation to fill in the blanks challenge

- mobile-app/lib/ui/views/learn/block/block_viewmodel.dart
- mobile-app/lib/ui/views/learn/challenge/challenge_viewmodel.dart
- mobile-app/lib/ui/views/learn/challenge/templates/template_viewmodel.dart
- mobile-app/lib/ui/views/learn/landing/landing_viewmodel.dart
Checklist:
This PR:
- Updates the app to use v2 of `/challenges` data
- This is just a simple version switch, there were no changes in the schema of the challenge JSON files
- Is related to #1426
> chore(viewmodel): use challenges data v2

- mobile-app/lib/ui/views/learn/challenge/templates/multiple_choice/multiple_choice_view.dart
The question text was centered:
<details><summary>Before</summary>
<p>
</p>
</details> 
<details><summary>After</summary>
<p>
</p>
</details>
> fix(multiple-choice): align question text to the start in MultipleChoiceView

- mobile-app/lib/ui/views/learn/challenge/templates/english/english_view.dart
- mobile-app/lib/ui/views/learn/challenge/templates/english/english_viewmodel.dart
> fix: fill in the blanks rendering layout

- mobile-app/lib/ui/views/learn/challenge/templates/english/english_view.dart
Checklist:
When the fill in the blank challenge is in the initial state, feedback doesn't show up. When the user tap the check button, the feedback section appears in the "Fill in the blank" section and pushes that section down. This might be disorienting as the user needs to re-adjust in order to continue to interact with the blanks / text fields. 
This PR swaps the placement of the "Feedback"  and "Fill in the blank" sections.
<details>
<summary>Screenshot</summary>
| --- | --- |
| <img width="410" alt="Screenshot 2025-05-16 at 01 31 09" src="https://github.com/user-attachments/assets/8626e698-4679-4280-903d-8bec89b93d7e" /> | <img width="410" alt="Screenshot 2025-05-16 at 01 29 51" src="https://github.com/user-attachments/assets/f24560e0-27c7-43d5-9c15-cf1ff6c82426" …
> fix(view): move feedback below fill in the blank section

- mobile-app/lib/l10n/app_en.arb
- mobile-app/lib/l10n/app_es.arb
- mobile-app/lib/l10n/app_pt.arb
- mobile-app/lib/ui/theme/fcc_theme.dart
- mobile-app/lib/ui/views/login/native_login_view.dart
Checklist:
This PR:
- Changes the submit button on login view to use gold + dark blue color combination
- Uses the correct placeholder text for the OTP input field
<details>
|  | Before | After |
| --- | --- | --- |
| Disabled | <img width="412" alt="Screenshot 2025-05-16 at 00 44 05" src="https://github.com/user-attachments/assets/d073e67a-6df6-43d5-b591-a2e0eba30717" /> | <img width="410" alt="Screenshot 2025-05-16 at 01 08 06" src="https://github.com/user-attachments/assets/8cb9ee8b-0e6c-4f63-bba8-9831728f3052" /> |
| Enabled | <img width="410" alt="Screenshot 2025-05-16 at 01 20 00" src="https://github.com/user-attachments/assets/c410561b-be50-4632-b3aa-8b5a0b85bbd5" /> | <img width="410" alt="Screenshot 2025-05-16 at 01 19 23" …
> fix(view): minor improvements to login view

- mobile-app/lib/ui/views/learn/challenge/templates/multiple_choice/multiple_choice_view.dart
Checklist:
Closes #1503
Tested on Odin - Learn HTML Foundations - Lesson A
| --- | --- |
| <img width="411" alt="Screenshot 2025-05-16 at 14 18 58" src="https://github.com/user-attachments/assets/d463ea88-9e71-4b0a-b44e-1f38fd2a4b52" /> | <img width="408" alt="Screenshot 2025-05-22 at 15 30 09" src="https://github.com/user-attachments/assets/c75d105c-a4ef-4b70-86e6-82945c433dd9" /> |
> fix(view): assignment checkbox

- mobile-app/lib/ui/views/learn/challenge/templates/review/review_view.dart
- mobile-app/lib/ui/views/learn/challenge/templates/review/review_viewmodel.dart
Checklist:
We now display code blocks with PhoneIDE, and apparently it is more expensive to rebuild the UI when PhoneIDE involves and the UI shifts / jumps when a rebuild happens.
Instead of calling `parser.parse()` every time the UI rebuilds, I'm creating the content once during initialization and use that for the display.
<details>
<summary>Screen recording</summary>
| --- | --- |
| https://github.com/user-attachments/assets/802450c9-e6c9-458a-a8d5-c79515c81b96 | https://github.com/user-attachments/assets/e36c3538-5d06-4312-a860-93575401c00b |
</details>
> fix(view, viewmodel): cache parsed html for review page

- mobile-app/lib/ui/views/learn/block/templates/grid/grid_view.dart
> fix(view): improve scroll behavior and layout in BlockGridView

- mobile-app/lib/ui/views/learn/widgets/pass/pass_widget_view.dart
Checklist:
This PR:
- Removes the close button from the PassWidgetView. The widget is now placed in an end drawer, so users can just swipe or tap outside to close it
- Closes #1589
<details>
<summary>Screenshot</summary>
</details>
> chore(view): remove close button from pass widget

- mobile-app/lib/service/learn/learn_file_service.dart
- mobile-app/lib/service/learn/learn_service.dart
- mobile-app/lib/ui/views/learn/challenge/challenge_view.dart
- mobile-app/lib/ui/views/learn/challenge/challenge_viewmodel.dart
Checklist:
This PR:
- Updates the file identifier to be `[fileName].[fileExtension]` instead of just file name. This is to ensure the uniqueness as React challenges can have both `index.jsx` and `index.html`
- Closes #1582 
I've tested and verified the following cases:
- React coding challenges are now accessible, file selection drowdown displays correctly
<details>
<summary>Screenshot</summary>
</details>
- Challenge reset is working as expected
- The file content are saved and retrieved correctly as expected
- Tests run on HTML, CSS, JS challenges correctly as expected
The tests fail on React challenges. It seems the user's code isn't passed to the tests. The tests can't see the code change and just run against the seed code.
I'm not sure if this is related to the test runner …
> fix(view, viewmodel, service): use full file name as file identifier

- mobile-app/lib/ui/views/learn/challenge/templates/multiple_choice/multiple_choice_view.dart
- mobile-app/lib/ui/views/learn/challenge/templates/python/python_view.dart
- mobile-app/lib/ui/views/learn/challenge/templates/review/review_view.dart
- mobile-app/lib/ui/views/learn/widgets/transcript_widget.dart
Checklist:
This PR:
- Updates `PythonView` to handle missing video
- Updates `Transcript` widget to accept an `isCollapsible` boolean. It should be collapsible when there is a video, otherwise the transcript is displayed as plain text
- Closes #1616
> fix(view): handle missing challenge video

- mobile-app/lib/ui/views/learn/challenge/templates/english/english_view.dart
- mobile-app/lib/ui/views/learn/challenge/templates/quiz/quiz_view.dart
- mobile-app/lib/ui/views/learn/challenge/templates/review/review_view.dart
- **fix(view): swap challenge instructions and description in English and Quiz views**
- **fix(view): swap parsed instructions and description in ReviewView**
Checklist:
Closes #1645
> fix: flip instructions and descriptions in multiple views
