freeCodeCamp/mobile

lib/models/forum_user_model.dart, lib/ui/views/forum/forum-user/forum_user_view.dart, lib/ui/views/forum/forum-user/forum_user_viewmodel.dart, pubspec.lock, pubspec.yaml
- it is now possible to view the Discourse badges correctly on the users profile page
before there was a placeholder image
=> fix: display discourse badges correctly

lib/models/forum_post_model.dart, lib/ui/views/forum/forum-comment/forum_comment_view.dart, lib/ui/views/forum/forum-post/forum_post_viewmodel.dart
=> fix: show discourse icons in comments

lib/ui/views/news/news-article-post/news_article_post_view.dart, lib/ui/views/news/news-feed/news_feed_view.dart, lib/ui/views/news/news_helpers.dart
- makes use of `LisView.separated`
- adds a background color to the thumbnail if a image is loading 
- changes the color of the loading Icon to white
- adds a background color to profile images
- removes the random border color function
- makes banners in articles look better at the top of the page by using `BoxFit.cover`
- makes author profile images look better by using `BoxFit.cover`
- makes code preview look better by using a horizontal Scroll-view.
=> fix: news ui improvements

lib/ui/widgets/drawer_widget/drawer_widget_view.dart, lib/ui/widgets/drawer_widget/drawer_widget_viewmodel.dart
this adds a devmode to the .env file, simply add `DEVELOPMENTMODE = true` in your .env file.
This temporarily removes the forum from the widget if dev mode is not enabled.
=> feat: devmode for drawer widget

lib/ui/views/news/news-feed/news_feed_view.dart
=> fix: space between author name and date

lib/app/app.dart, lib/app/app.locator.dart, lib/service/episode_audio_service.dart, lib/ui/views/podcast/episode/episode_view.dart, lib/ui/views/podcast/episode/episode_viewmodel.dart
* Episodes will play in bg until a different episode is played or  paused in the notification. Previously, the episode would stop playing the moment the respective episode view was closed which isn't ideal.
* Added a loader so the user knows the audio is being loaded/buffered
* Made the audio player part into a service
=> feat: make audio service and fix bugs

lib/ui/views/podcast/podcast-list/podcast_list_view.dart
* Fix bug where podcast title isn't shown in smaller screens in podcast view
=> Final podcast fixes

sample.env
Reverts freeCodeCamp/mobile#109
=> Revert "fix: update sample env with news key"

mobile-app/lib/ui/views/forum/forum-html-handler/forum_html_handler.dart, mobile-app/lib/ui/widgets/drawer_widget/drawer_widget_viewmodel.dart
this should fix most of the null errors on the forum.
There are still some weird image errors showing up though.
(it is pretty unstable)
=> fix: null error on forum

mobile-api/src/index.ts
Increasing the interval time from every 5 minutes to 30 minutes.
=> increase data update interval time

mobile-app/lib/ui/views/learn/learn_viewmodel.dart
I forgot the change I had requested in #214 until after I had merged the PR 🤦‍♂️.
=> fix: wording for learn dialog

mobile-app/android/app/build.gradle, mobile-app/android/build.gradle
=> fix: update versions for flutter 2.10 build

.github/workflows/flutter-ci.yml
* Caches work for PRs
* The action will run daily at midnight UTC
* Clearer names for each step of the action
=> feat(ci): caches, daily run and step names

mobile-app/lib/ui/views/news/news-feed/news_feed_view.dart
Made some minor improvements to the news view.
=> fix: dry out news feed (again)

mobile-app/lib/ui/views/news/html_handler/html_handler.dart, mobile-app/lib/ui/views/news/news-article/news_article_view.dart, mobile-app/lib/ui/views/news/news-article/news_article_viewmodel.dart, mobile-app/lib/ui/views/news/news-bookmark/news_bookmark_view.dart, mobile-app/lib/ui/views/news/news-bookmark/news_bookmark_viewmodel.dart, mobile-app/lib/ui/views/news/news-bookmark/news_bookmark_widget.dart
=> feat: lazy loading on bookmarked articles

mobile-api/.eslintrc.js, mobile-api/package-lock.json, mobile-api/package.json, mobile-api/src/db-connect.ts, mobile-api/src/index.ts
Checklist:
Hey @Nirajn2311 as I was going through trying to fix the lint issues I realised it was encouraging me to changing the api's behaviour a bit.  So, to stop the creeping the scope too much, I figured I'd create the PR as is.  If you're happy with this PR we can fix the remaining lint issues at a later date.
Sound good?
P.S. would you like me to set up prettier, too?
=> chore: add linting

mobile-api/src/db-connect.ts, mobile-api/src/jobs/update-podcasts.ts, mobile-api/src/models/Episode.ts, mobile-api/src/models/Podcast.ts
Checklist:
Hey @Nirajn2311, mostly this just defines and fixes up types, but `duration` doesn't seem to exist in the feed, so I dropped it from the Episode model.  This felt pretty serious, so I thought I'd create the PR as is so you could take a look.
=> fix: remove unused duration property

.github/workflows/test-api.yml
Checklist:
It won't pass, yet, but I'm gradually getting on top of the lint issues.
=> chore: enable linting of the api

mobile-api/src/models/Episode.ts, mobile-api/src/models/Podcast.ts, mobile-api/src/routes.ts
Hi again @Nirajn2311 Another day, another bit of refactoring!
This time I stopped because I wasn't sure how you wanted to handle missing Podcasts or Episodes.  I just made it throw, for now, to keep TypeScript happy.
=> refactor: fix lint issues in routes

LICENSE.md
=> fix: update license to 2022

.github/workflows/test-api.yml
=> feat: test in workflow

mobile-app/lib/service/authentication_service.dart, mobile-app/pubspec.lock, mobile-app/pubspec.yaml
* Fixed a bug where dio options where set after initial fetch of user object which would lead to an error for that fetch request
* Fixed a bug where in-app browser wasn't being disposed leading to them being run in the background after closing the browser.
* Added two interceptors for Dio for debugging purposes during development
=> feat: fix dio bug and add interceptors for dev

mobile-app/lib/app/app.dart, mobile-app/lib/app/app.router.dart, mobile-app/lib/models/main/user_model.dart, mobile-app/lib/service/authentication_service.dart, mobile-app/lib/service/test_service.dart, mobile-app/lib/ui/views/profile/profile_viemodel.dart, mobile-app/lib/ui/views/profile/profile_view.dart, mobile-app/lib/ui/widgets/drawer_widget/drawer_widget_view.dart, mobile-app/lib/ui/widgets/drawer_widget/drawer_widget_viewmodel.dart, mobile-app/pubspec.lock, mobile-app/pubspec.yaml
Displays logged in users profile
=> feat: profile component

mobile-app/lib/models/podcasts/episodes_model.dart, mobile-app/lib/service/podcasts_service.dart, mobile-app/lib/ui/views/podcast/episode-list/episode_list_view.dart, mobile-app/lib/ui/views/podcast/episode-list/episode_list_viewmodel.dart, mobile-app/lib/ui/views/podcast/episode/episode_viewmodel.dart, mobile-app/lib/ui/views/podcast/podcast-list/podcast_list_viewmodel.dart
Linting was not yet enabled on the pr.
=> fix: podcast lint errors

mobile-app/integration_test/news_test.dart, mobile-app/lib/app/app.locator.dart, mobile-app/lib/app/app.logger.dart, mobile-app/lib/app/app.router.dart, mobile-app/lib/main.dart, mobile-app/lib/service/authentication_service.dart, mobile-app/lib/ui/views/learn/learn_view.dart, mobile-app/lib/ui/views/learn/learn_viewmodel.dart, mobile-app/lib/ui/views/profile/profile_view.dart, mobile-app/lib/ui/widgets/drawer_widget/drawer_widget_viewmodel.dart, mobile-app/lib/ui/widgets/login_webview_widget/login_webview_view.dart, mobile-app/lib/ui/widgets/login_webview_widget/login_webview_viewmodel.dart, mobile-app/pubspec.lock, mobile-app/pubspec.yaml
* Upgrade `stacked` packages
* Replace `flutter_webview_plugin` with `webview_flutter`
* Also integration test warnings have been fixed 😃
=> feat(app): replace and upgrade packages

README.md
=> chore: update chat to Discord

mobile-app/lib/app/app.router.dart, mobile-app/lib/ui/views/learn/challenge_editor/challenge_model.dart, mobile-app/lib/ui/views/learn/challenge_editor/challenge_view.dart, mobile-app/lib/ui/views/learn/learn-builders/challenge-builder/challenge_builder_grid_view.dart, mobile-app/lib/ui/views/learn/learn-builders/challenge-builder/challenge_builder_list_view.dart, mobile-app/lib/ui/views/learn/learn-builders/challenge-builder/challenge_builder_model.dart, mobile-app/lib/ui/views/learn/widgets/description/description_widget_view.dart
* Show instructions panel on first open
* Show the right state of the instructions button
This PR will finish the remaining points of "Instructions pane"(Issue #449) after PR #470 is merged
=> feat: instructions panel

.github/workflows/test-image.yml, mobile-api/package-lock.json, mobile-api/package.json, mobile-api/src/index.ts
Docker image is reduced to 144 from 228 mb
=> chore(api): reduce container size

mobile-app/lib/app/app.dart, mobile-app/lib/app/app.router.dart, mobile-app/lib/service/authentication_service.dart, mobile-app/lib/ui/views/web_view/web_view_model.dart, mobile-app/lib/ui/views/web_view/web_view_view.dart, mobile-app/lib/ui/widgets/drawer_widget/drawer_web_buttton.dart, mobile-app/lib/ui/widgets/drawer_widget/drawer_widget_view.dart, mobile-app/lib/ui/widgets/drawer_widget/drawer_widget_viewmodel.dart
=> feat: drawer improvements and privacy page

mobile-app/pubspec.lock, mobile-app/pubspec.yaml
=> chore: update to version 2.2.1

mobile-app/lib/ui/views/learn/challenge_editor/challenge_model.dart, mobile-app/lib/ui/views/learn/challenge_editor/challenge_view.dart, mobile-app/lib/ui/views/learn/widgets/custom_bottom_bar/custom_bottom_bar.dart, mobile-app/lib/ui/views/learn/widgets/custom_tab_bar/custom_tab_bar.dart, mobile-app/pubspec.lock
To be merged along with - https://github.com/freeCodeCamp/PhoneIDE/pull/20
=> feat: updated syntax highlighter

mobile-app/lib/ui/views/news/html_handler/html_handler.dart
This makes everything a little less big.
=> fix: adjust title sizes again

mobile-app/lib/app/app.dart, mobile-app/lib/app/app.locator.dart, mobile-app/lib/models/learn/challenge_model.dart, mobile-app/lib/service/authentication_service.dart, mobile-app/lib/service/learn_service.dart, mobile-app/lib/ui/views/learn/widgets/pass/pass_widget_model.dart
This PR creates the Learn service which we'll be using for submitting users challenges/projects to the right API endpoint. I've created the submit function for the pass panel but I've not connected it to the UI yet as tests are not currently working.
=> feat: learn service

mobile-app/lib/ui/views/learn/widgets/description/description_widget_view.dart
=> fix: always display any instruciton or description

mobile-app/lib/ui/views/learn/challenge_editor/challenge_model.dart, mobile-app/lib/ui/views/learn/challenge_editor/challenge_view.dart
=> fix: do not hide appbar when editing

mobile-app/lib/ui/views/learn/challenge_editor/challenge_model.dart, mobile-app/lib/ui/views/learn/challenge_editor/challenge_view.dart, mobile-app/lib/ui/views/learn/test_runner.dart
https://user-images.githubusercontent.com/46919888/191227204-e1424813-fbc4-4459-b82e-e8fdf50d97e0.mp4
=> feat: show tests running

mobile-app/lib/ui/views/learn/learn/learn_view.dart, mobile-app/lib/ui/views/learn/widgets/pass/pass_widget_view.dart
=> chore: disable login buttons

mobile-app/lib/ui/views/learn/learn/learn_model.dart
=> fix: give fallback of false superblocks

mobile-app/lib/service/learn_service.dart, mobile-app/lib/ui/views/learn/challenge_editor/challenge_model.dart, mobile-app/lib/ui/views/learn/learn-builders/challenge-builder/challenge_builder_grid_view.dart, mobile-app/lib/ui/views/learn/learn-builders/challenge-builder/challenge_builder_list_view.dart, mobile-app/lib/ui/views/learn/learn/learn_model.dart
=> fix: use right domain in production

mobile-app/lib/ui/theme/fcc_theme.dart
=> fix: text selection bar blending in with background

README.md
=> fix: wording read me

mobile-app/lib/ui/views/learn/challenge_editor/challenge_model.dart, mobile-app/lib/ui/views/learn/learn-builders/block-builder/block_builder_model.dart, mobile-app/lib/ui/views/learn/learn-builders/challenge-builder/challenge_builder_list_view.dart, mobile-app/lib/ui/views/learn/learn-builders/superblock_builder.dart
=> fix: filter out es6 and first block open if cache is empty

mobile-app/lib/ui/views/learn/challenge_editor/challenge_model.dart, mobile-app/lib/ui/views/learn/challenge_editor/challenge_view.dart
- feat: parse challenge view better
this does not fix what the branch says it does.
=> chore: improvements on challenge view

mobile-app/lib/ui/views/learn/challenge_editor/challenge_view.dart
=> fix: disabled run button

mobile-app/pubspec.yaml
=> release(app): v3.0.1+30001

mobile-api/src/__tests__/podcast.test.ts, mobile-api/src/podcast-feed-urls.json, mobile-app/lib/ui/views/podcast/episode-list/episode_list_view.dart
* Add 2 new podcast
* CodeNewbie
* Scrimba
* Fix the "Show more" button design in episode list view
* Fix the API tests
=> feat(api): add 2 new podcasts

mobile-app/lib/ui/views/podcast/podcast-list/podcast_list_view.dart, mobile-app/lib/ui/views/podcast/podcast-list/podcast_list_viewmodel.dart
=> chore: add error message podcasts

mobile-app/lib/ui/views/learn/learn-builders/challenge-builder/challenge_builder_grid_view.dart
=> Fix: Spell Project correctly in the Learn grid view

.github/workflows/mobile-curriculum-e2e.yml, mobile-app/lib/main.dart
**NOTE**: To be merged after freeCodeCamp/freeCodeCamp#48612
=> action: mobile curriculum tests CI

mobile-app/lib/ui/views/forum/forum-post/forum_post_viewmodel.dart, mobile-app/lib/ui/views/news/news-article/news_article_view.dart, mobile-app/pubspec.lock, mobile-app/pubspec.yaml
=> chore(app): clear and update dependencies

mobile-app/lib/ui/views/learn/learn-builders/block-builder/block_builder_view.dart, mobile-app/lib/ui/views/learn/learn-builders/challenge-builder/challenge_builder_grid_view.dart, mobile-app/lib/ui/views/learn/learn-builders/challenge-builder/challenge_builder_list_view.dart, mobile-app/lib/ui/views/learn/learn-builders/challenge-builder/challenge_builder_model.dart, mobile-app/lib/ui/views/learn/learn-builders/superblock_builder.dart, mobile-app/lib/ui/views/learn/learn/learn_view.dart, mobile-app/lib/ui/views/learn/widgets/custom_tab_bar/custom_tab_bar.dart, mobile-app/lib/ui/views/learn/widgets/description/description_widget_view.dart, mobile-app/lib/ui/views/learn/widgets/dynamic_panel/dynamic_panel.dart, mobile-app/lib/ui/views/learn/widgets/pass/pass_widget_view.dart
=> chore: parse learn files

README.md
=> chore: update read me

mobile-app/lib/main.dart, mobile-app/lib/service/learn/learn_offline_service.dart, mobile-app/lib/ui/views/learn/learn-builders/challenge-builder/challenge_builder_grid_view.dart, mobile-app/lib/ui/views/learn/learn-builders/challenge-builder/challenge_builder_model.dart
=> chore: hide download button for now

mobile-app/lib/ui/views/news/html_handler/html_handler.dart
=> fix: back button outline

mobile-app/lib/service/authentication/authentication_service.dart, mobile-app/lib/ui/widgets/drawer_widget/drawer_web_buttton.dart
=> feat(app): track web view location for GA

mobile-app/lib/service/news/bookmark_service.dart
=> fix: newest bookmark ontop

.github/workflows/flutter-ci.yml, .github/workflows/flutter-deploy.yml, mobile-app/pubspec.yaml
Checklist:
The BIG release :rocket:. It's finally here
=> release(app): v3.1.0+30100

mobile-app/sample.env
=> fix: remove forum from sample.env

.github/workflows/deploy-api.yml, .github/workflows/mobile-curriculum-e2e.yml, .github/workflows/test-api.yml, .github/workflows/test-image.yml, mobile-app/lib/ui/views/news/news-tutorial/news_tutorial_viewmodel.dart, mobile-app/lib/ui/widgets/drawer_widget/drawer_widget_view.dart, mobile-app/lib/ui/widgets/drawer_widget/drawer_widget_viewmodel.dart, mobile-app/pubspec.lock, mobile-app/pubspec.yaml
Checklist:
* Fixes bug in deployment action
* Migrate main repo scripts to use pnpm
* Make drawer scrollable for smaller screens
=> fix: bugs in latest release

mobile-app/pubspec.yaml
=> release(app): v3.1.1+30101

mobile-app/lib/service/learn/learn_offline_service.dart, mobile-app/lib/ui/views/learn/block/block_view.dart, mobile-app/lib/ui/views/learn/block/block_viewmodel.dart
=> fix: download UI

mobile-app/lib/service/firebase/analytics_observer.dart
Checklist:
Closes #XXXXX
Record challenge ID for GA instead of whole object. This change will also be going in with the next stable release.
=> chore: record challenge id for GA

mobile-app/pubspec.yaml
=> release(app): v3.1.2+30102

mobile-app/android/app/src/main/AndroidManifest.xml
This Pull Request reopens the original PR #862 which was closed by accident. 
Checklist:
Closes #807
Here is a [summary and a test plan](https://docs.google.com/document/d/10C37v96CIIIm7pPFwwFgrx9tAetuSSVom-1hZCXgEeQ/edit?usp=sharing) that describes the steps we took to fix the issue.
Collaborators:
@Cao1224
@meganchung4444
Mentor:
@donaldong
=> Fix of "Unwanted gap between Code and Camp"

mobile-app/pubspec.yaml
=> release(app): v3.2.1+30201

mobile-app/lib/ui/views/learn/challenge/challenge_view.dart, mobile-app/lib/ui/views/learn/challenge/challenge_viewmodel.dart
=> fix: old state when returning to block page

mobile-app/lib/ui/widgets/tutorial_list_widget.dart
=> fix: author profile tutorial list widget

mobile-app/lib/service/authentication/authentication_service.dart
Checklist:
Closes #XXXXX
This will help us by letting the users to send the error stacktrace which would in turn help in debugging the issue. I'll be working on adding Firebase Crashlytics in the coming weeks in a separate PR so we can handle most errors without having to ask for users to email us.
=> feat: option to email support login error

mobile-app/pubspec.yaml
=> release(app): v3.2.2+30202

mobile-app/pubspec.yaml
=> release(app): v3.2.3+30203

mobile-app/lib/ui/views/learn/widgets/dynamic_panel/panels/pass/pass_widget_view.dart
=> feat: add "Next" button in pass panel

.github/workflows/mobile-curriculum-e2e.yml
Checklist:
Closes #XXXXX
Mobile curriculum action is failing as main repo using PNPM v8.
=> chore: update pnpm version

mobile-app/lib/ui/views/learn/widgets/dynamic_panel/panels/pass/pass_widget_view.dart
=> fix: old state pass panel

mobile-app/lib/models/main/profile_ui_model.dart, mobile-app/lib/models/main/user_model.dart
=> fix: login issues

.github/workflows/mobile-curriculum-e2e.yml
=> fix: mobile curriculum test

mobile-app/pubspec.yaml
=> release(app): v3.3.0+30300

.github/workflows/flutter-ci.yml, .github/workflows/flutter-deploy.yml, mobile-app/ios/Podfile, mobile-app/ios/Podfile.lock, mobile-app/ios/Runner/Info-Debug.plist, mobile-app/ios/Runner/Info-Profile.plist, mobile-app/ios/Runner/Info-Release.plist
=> fix: ios issues

mobile-app/lib/ui/views/learn/challenge/challenge_view.dart
=> fix: back button for challenge view

mobile-app/lib/ui/views/learn/challenge/challenge_view.dart, mobile-app/lib/ui/views/learn/challenge/challenge_viewmodel.dart, mobile-app/lib/ui/views/learn/widgets/dynamic_panel/panels/dynamic_panel.dart, mobile-app/lib/ui/views/learn/widgets/dynamic_panel/panels/hint/hint_widget_view.dart, mobile-app/lib/ui/views/news/html_handler/html_handler.dart, mobile-app/pubspec.lock, mobile-app/pubspec.yaml
=> fix: update phone_ide imports

mobile-app/lib/service/navigation/quick_actions_service.dart, mobile-app/lib/ui/widgets/drawer_widget/drawer_widget_view.dart
=> feat: disable code radio for iOS build

mobile-app/pubspec.yaml
=> chore: release 3.3.2

mobile-app/lib/ui/views/learn/widgets/dynamic_panel/panels/pass/pass_widget_view.dart
=> fix: passpane login issue

mobile-app/lib/ui/views/login/native_login_view.dart, mobile-app/lib/ui/views/login/native_login_viewmodel.dart
=> chore: hide apple button

mobile-app/lib/models/main/user_model.dart
Checklist:
Closes #XXXXX
The user object now doesn't include the `is*` values as discussed in last weeks API meeting so this PR updates the user object.
Ref: https://github.com/freeCodeCamp/freeCodeCamp/pull/50346
=> chore: remove unused values

mobile-app/pubspec.yaml
=> release(app): v3.3.3+30303

mobile-app/lib/ui/views/login/native_login_view.dart, mobile-app/lib/ui/views/login/native_login_viewmodel.dart
=> chore: remove dev wall on native login screen

mobile-app/lib/models/main/profile_ui_model.dart
I wonder if the value from the user object will be. But this should fix some crashlytics issues
https://console.firebase.google.com/u/1/project/mobile-4ee8a/crashlytics/app/android:org.freecodecamp/issues/8076a4bfad6efb1cd4efcfdb3cd42169?time=last-seven-days&sessionEventKey=646524CD02300001138B034F22895EB8_1812674539297487694
=> fix: possible values profile ui

mobile-app/lib/app/app.dart, mobile-app/lib/app/app.router.dart, mobile-app/lib/ui/views/settings/delete-account/delete_account_view.dart, mobile-app/lib/ui/views/settings/delete-account/delete_account_viewmodel.dart, mobile-app/lib/ui/views/settings/settings_view.dart, mobile-app/lib/ui/views/settings/settings_viewmodel.dart, mobile-app/lib/ui/widgets/drawer_widget/drawer_widget_view.dart, mobile-app/lib/ui/widgets/drawer_widget/drawer_widget_viewmodel.dart, mobile-app/pubspec.lock
=> feat: add settings page

mobile-app/lib/ui/views/login/native_login_view.dart
=> fix: button text native login

mobile-app/lib/models/learn/challenge_model.dart, mobile-app/lib/service/learn/learn_offline_service.dart, mobile-app/lib/service/learn/learn_service.dart, mobile-app/lib/ui/views/learn/block/block_view.dart, mobile-app/lib/ui/views/learn/block/block_viewmodel.dart, mobile-app/lib/ui/views/learn/challenge/challenge_viewmodel.dart, mobile-app/lib/ui/views/learn/landing/landing_viewmodel.dart, mobile-app/lib/ui/views/learn/superblock/superblock_viewmodel.dart, mobile-app/lib/ui/views/learn/widgets/dynamic_panel/panels/hint/hint_widget_view.dart, mobile-app/test/unit/learn_file_controller_test.dart, mobile-app/test/widget_test.dart
=> feat: update challenge links

mobile-app/pubspec.lock, mobile-app/pubspec.yaml
Checklist:
With this PR we can prepare another build for iOS as this one fixes a bug users faced while logging in(different system language breaking auth0 package)
=> chore: update auth0

mobile-app/pubspec.yaml
=> release(app): v3.4.1+30401

mobile-app/lib/app/app.router.dart, mobile-app/lib/ui/views/news/html_handler/html_handler.dart, mobile-app/lib/ui/views/news/news-image-viewer/news_image_view.dart, mobile-app/lib/ui/views/podcast/episode/episode_view.dart, mobile-app/lib/ui/widgets/podcast_widgets/podcast_tilte_widget.dart, mobile-app/pubspec.lock
Checklist:
While some are iOS related but most bugs appear in both Android and iOS
Crashlytics reports of resolved bugs:
* https://console.firebase.google.com/u/1/project/mobile-4ee8a/crashlytics/app/ios:org.freecodecamp.ios/issues/9c52fba9971be1ff8e9bbfa154b90bd6
* https://console.firebase.google.com/u/1/project/mobile-4ee8a/crashlytics/app/ios:org.freecodecamp.ios/issues/dc3d682023cc9b35ee755128e1876114
* https://console.firebase.google.com/u/1/project/mobile-4ee8a/crashlytics/app/ios:org.freecodecamp.ios/issues/28853bed197cfd0668872664c84b2502
=> fix: iOS bugs

mobile-app/lib/ui/widgets/drawer_widget/drawer_widget_view.dart
=> fix: freeCodeCamp info in drawer by adding a SafeArea

mobile-app/lib/ui/views/podcast/podcast-list/podcast_list_view.dart
=> feat: add background color podcast tile

mobile-app/lib/ui/views/learn/challenge/challenge_viewmodel.dart, mobile-app/lib/ui/views/settings/settings_viewmodel.dart, mobile-app/lib/ui/widgets/setup_dialog_ui.dart
=> fix: dismissible dialogs

mobile-app/lib/ui/views/news/news-tutorial/news_tutorial_viewmodel.dart
=> fix: bookmarked tutorials not viewable

mobile-app/lib/ui/views/learn/widgets/dynamic_panel/panels/hint/hint_widget_view.dart
=> fix: overflowing text in hint panel

mobile-app/pubspec.lock, mobile-app/pubspec.yaml
=> fix: potentially fix quick actions ?

mobile-app/lib/ui/views/news/news-bookmark/news_bookmark_view.dart, mobile-app/lib/ui/views/news/news-bookmark/news_bookmark_viewmodel.dart, mobile-app/lib/ui/views/news/news-tutorial/news_tutorial_view.dart, mobile-app/lib/ui/views/news/news-tutorial/news_tutorial_viewmodel.dart, mobile-app/lib/ui/views/news/widgets/back_to_top_button.dart
=> feat: top to article button

mobile-app/lib/app/app.router.dart, mobile-app/lib/enums/dialog_type.dart, mobile-app/lib/ui/views/settings/delete-account/delete_account_view.dart, mobile-app/lib/ui/views/settings/delete-account/delete_account_viewmodel.dart, mobile-app/lib/ui/widgets/setup_dialog_ui.dart, mobile-app/pubspec.yaml
=> release(app): v3.5.0+30500

mobile-app/lib/models/learn/challenge_model.dart, mobile-app/lib/service/learn/learn_service.dart, mobile-app/lib/ui/views/learn/challenge/challenge_view.dart, mobile-app/lib/ui/views/learn/challenge/challenge_viewmodel.dart, mobile-app/lib/ui/views/learn/challenge/templates/python-project/python_project_view.dart, mobile-app/lib/ui/views/learn/challenge/templates/python-project/python_project_viewmodel.dart, mobile-app/lib/ui/views/learn/challenge/templates/python/python_view.dart, mobile-app/lib/ui/views/learn/challenge/templates/python/python_viewmodel.dart, mobile-app/lib/ui/views/learn/widgets/dynamic_panel/panels/hint/hint_widget_view.dart, mobile-app/lib/ui/views/learn/widgets/dynamic_panel/panels/pass/pass_widget_model.dart, mobile-app/lib/ui/views/learn/widgets/dynamic_panel/panels/pass/pass_widget_view.dart, mobile-app/lib/ui/views/news/html_handler/html_handler.dart, mobile-app/pubspec.lock
Checklist:
A wild 🐍  is slithering into the app
TODO:
=> feat: python certification

mobile-app/lib/service/authentication/authentication_service.dart, mobile-app/lib/service/learn/learn_service.dart
=> fix: logout if fetch user request errors

mobile-app/lib/ui/views/learn/challenge/challenge_viewmodel.dart, mobile-app/pubspec.yaml
=> chore: release 4.0.0

mobile-app/lib/models/learn/curriculum_model.dart
=> fix: superblock data format

mobile-app/pubspec.yaml
=> release(app): v4.0.1+40001

mobile-app/ios/Runner/Info-Debug.plist, mobile-app/ios/Runner/Info-Profile.plist, mobile-app/ios/Runner/Info-Release.plist
This will stop showing the dialog in App Store Connect asking if the app uses any non-exempt encryption.
Checklist:
Closes #XXXXX
=> feat: add non-exempt encryption config value

mobile-app/lib/ui/views/learn/landing/landing_view.dart
=> fix: offline message learn

mobile-app/lib/models/learn/curriculum_model.dart, mobile-app/pubspec.yaml
=> release(app): v4.1.0+40100

.github/workflows/flutter-deploy.yml
=> feat: on-demand prod action

mobile-app/pubspec.yaml
=> chore(release): v4.1.1

mobile-app/lib/app/app.dart, mobile-app/lib/app/app.locator.dart, mobile-app/lib/main.dart, mobile-app/lib/service/authentication/authentication_service.dart, mobile-app/lib/service/dio_service.dart, mobile-app/lib/service/learn/learn_offline_service.dart, mobile-app/lib/service/learn/learn_service.dart, mobile-app/lib/service/podcast/download_service.dart, mobile-app/lib/ui/views/learn/challenge/challenge_viewmodel.dart, mobile-app/lib/ui/views/learn/landing/landing_viewmodel.dart, mobile-app/lib/ui/views/learn/superblock/superblock_viewmodel.dart, mobile-app/lib/ui/views/login/native_login_viewmodel.dart, mobile-app/lib/ui/views/news/news-author/news_author_viewmodel.dart, mobile-app/lib/ui/views/news/news-feed/news_feed_viewmodel.dart, mobile-app/lib/ui/views/news/news-tutorial/news_tutorial_viewmodel.dart, mobile-app/lib/ui/views/podcast/episode-list/episode_list_viewmodel.dart, mobile-app/lib/ui/views/podcast/podcast-list/podcast_list_viewmodel.dart, mobile-app/lib/ui/views/settings/delete-account/delete_account_viewmodel.dart, mobile-app/lib/ui/widgets/podcast_widgets/podcast_tilte_widget.dart, mobile-app/lib/ui/widgets/tutorial_list_widget.dart
=> feat: dio service

mobile-app/lib/enums/challenge_test_state_type.dart, mobile-app/lib/models/learn/challenge_model.dart
=> fix: remove challenge test enum

.github/workflows/crowdin-download.yml, .github/workflows/crowdin-upload.yml
=> chore(i18n): prepare crowdin workflows

mobile-app/lib/models/code-radio/code_radio_model.dart
=> fix: remove genre from coderadio

mobile-app/lib/l10n/app_en.arb, mobile-app/lib/ui/views/code_radio/code_radio_view.dart, mobile-app/lib/ui/views/code_radio/code_radio_viewmodel.dart
Checklist:
Closes #1103 
I've also added the default error message to be shown in case the coderadio view errors out when fetching data.
=> feat: update code radio websocket url

mobile-api/src/podcast-feed-urls.json
Checklist:
guidelines](https://contribute.freecodecamp.org).
title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)
=> feat: added freeCodeCamp Podcast en Español

mobile-api/src/__tests__/podcast.test.ts, mobile-api/src/podcast-feed-urls.json
Checklist:
guidelines](https://contribute.freecodecamp.org).
title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)
=> feat: added freeCodeCamp Podcast in Chinese

mobile-app/lib/ui/views/learn/challenge/templates/python/python_view.dart
Checklist:
Closes #XXXXX
To be merged after changes in https://github.com/freeCodeCamp/PhoneIDE/pull/55 are published
=> fix: challenge bugs

mobile-app/pubspec.lock, mobile-app/pubspec.yaml, mobile-app/test/widget_test.dart
=> chore: update phoneIDE version

mobile-app/lib/ui/views/podcast/podcast-list/podcast_list_viewmodel.dart, mobile-app/lib/ui/views/podcast/podcast_urls.dart, mobile-app/lib/ui/widgets/podcast_widgets/podcast_tilte_widget.dart
=> feat: display fcc podcasts first

mobile-app/pubspec.yaml
=> release(app): v4.1.2+40102

mobile-app/lib/ui/views/learn/challenge/templates/python-project/python_project_viewmodel.dart, mobile-app/lib/ui/views/learn/challenge/templates/python/python_view.dart, mobile-app/lib/ui/views/news/html_handler/html_handler.dart, mobile-app/lib/ui/views/news/news-feed/news_feed_view.dart, mobile-app/lib/ui/views/podcast/episode/episode_view.dart
Checklist:
Closes #XXXXX
Firebase Crashlytics reports closed in this PR:
* https://console.firebase.google.com/u/1/project/mobile-4ee8a/crashlytics/app/ios:org.freecodecamp.ios/issues/34fc5a0fce078b6a1e0872fa69ab2393?time=last-seven-days&types=crash - On clicking the LinkedIn link present in the [article](https://www.freecodecamp.org/news/podcast-learning-to-code-in-your-30s-patrick-san-juan/) an error is thrown internally and the link won't open.
* https://console.firebase.google.com/u/1/project/mobile-4ee8a/crashlytics/app/android:org.freecodecamp/issues/41742e679a7af85d06e5dc286666b36d?time=last-seven-days&sessionEventKey=64FF0CB501A3000D30745D979D9A5675_1855995099788877513 - Same error as above one but in Android
* https://console.firebase.google.com/u/1/project/mobile-4ee8a/crashlytic …
=> fix: firebase crashlytics reports part 1

mobile-api/src/podcast-feed-urls.json, mobile-app/lib/ui/views/podcast/podcast-list/podcast_list_viewmodel.dart
=> feat: fcc portuguese podcast

mobile-app/pubspec.yaml
=> chore: release v4.1.3

mobile-app/lib/models/main/user_model.dart
=> fix: remove sound attribute from the user model

mobile-app/android/app/build.gradle
Reverts freeCodeCamp/mobile#1131
=> Revert "fix(deps): update dependency com.google.android.material:material to v1.10.0"

.github/workflows/mobile-curriculum-e2e.yml
=> fix: mobile curriculum e2e test

mobile-app/pubspec.yaml
=> chore: release v4.1.5

.github/workflows/mobile-curriculum-e2e.yml, mobile-app/test/widget_test.dart
=> fix: curriculum file location

mobile-app/lib/models/learn/challenge_model.dart, mobile-app/lib/ui/views/learn/challenge/templates/python/python_view.dart
Checklist:
Closes #1151 
This PR(https://github.com/freeCodeCamp/freeCodeCamp/pull/51942) changed the schema of the MCQ challenges. 
Crashlytics report:
* https://console.firebase.google.com/u/1/project/mobile-4ee8a/crashlytics/app/ios:org.freecodecamp.ios/issues/f76a19f04cc5c5593fb9d55631d54e52?time=last-seven-days&sessionEventKey=2557aadcab734a0d9354ea5f5052fb36_1879317416740816262
* https://console.firebase.google.com/u/1/project/mobile-4ee8a/crashlytics/app/android:org.freecodecamp/issues/4cc6294bb8148e28a3b7e7b5b5932b38?time=last-seven-days&sessionEventKey=6551E98C017600030844D0EEB25F8EC9_1879319191106985057
=> fix: mcq challenge schema

mobile-app/pubspec.yaml
=> release(app): v4.1.6+40106

mobile-app/pubspec.yaml
=> release(app): v4.1.7+40107

mobile-app/lib/ui/views/learn/test_runner.dart
Checklist:
ref https://github.com/freeCodeCamp/freeCodeCamp/pull/52466
=> chore: update curriculum helpers to v1.2.0

mobile-app/lib/ui/views/learn/landing/landing_viewmodel.dart
… #1167
Checklist:
- I have solved issue  #1167 In the Learn section clicking an unsupported cert/path permanent pop-up. 
- fixed this by adding future delay to snackbar
=> fix: auto dismiss toast for unavailable superblocks

mobile-app/lib/ui/views/podcast/podcast-list/podcast_list_view.dart
=> fix: Title of podcast should be truncated with dots if the text doesn't fit in its container.

mobile-app/lib/ui/views/learn/test_runner.dart
=> chore: update curriculum helpers

mobile-app/lib/ui/views/profile/profile_view.dart
Checklist:
Resolves - https://console.firebase.google.com/u/1/project/mobile-4ee8a/crashlytics/app/ios:org.freecodecamp.ios/issues/9c52fba9971be1ff8e9bbfa154b90bd6?time=1698710400000:1701302399000&sessionEventKey=73bb2d6eff8b4a12a939f074dac94d84_1885473242162746261
I'm not checking for base64 images as we know those are not allowed anymore
=> fix: empty profile image

mobile-app/lib/ui/views/learn/challenge/challenge_view.dart, mobile-app/lib/ui/views/learn/challenge/templates/odin/odin_view.dart, mobile-app/lib/ui/views/learn/challenge/templates/python-project/python_project_view.dart, mobile-app/lib/ui/views/learn/challenge/templates/python/python_view.dart
Checklist:
With the actions stuck in the queue the Odin Project PR missed out on the analyzer check
=> fix: analyzer issues

package-lock.json, package.json
Checklist:
Workspaces was not setup properly and the current setup is easier to manage the API deps. If in the future we add more services, then we can make use of workspaces or PNPM.
=> chore: remove workspaces

.github/workflows/crowdin-download.yml, .github/workflows/deploy-api.yml, .github/workflows/mobile-curriculum-e2e.yml, .github/workflows/test-api.yml, .github/workflows/test-image.yml, mobile-api/Dockerfile
=> chore: use node 20 in actions

.github/workflows/test-image.yml
Checklist:
Build API workflow is failing because GH Actions removed v1 of docker compose - https://github.com/actions/runner-images/issues/9557
=> chore: migrate to docker compose v2

.github/workflows/flutter-deploy.yml, mobile-app/android/Gemfile.lock
=> chore: update ruby

mobile-app/pubspec.yaml
=> release(app): v4.1.9+40109

mobile-app/lib/constants/radio_articles.dart, mobile-app/lib/ui/views/news/news-feed/news_feed_viewmodel.dart, mobile-app/lib/ui/views/news/news-search/news_search_view.dart, mobile-app/lib/ui/views/news/news-search/news_search_viewmodel.dart, mobile-app/pubspec.lock, mobile-app/pubspec.yaml
=> feat: migrate to official algolia package

mobile-app/lib/ui/views/learn/challenge/challenge_view.dart, mobile-app/lib/ui/views/learn/widgets/dynamic_panel/panels/pass/pass_widget_view.dart, mobile-app/pubspec.lock, mobile-app/pubspec.yaml
=> feat: replace FA icons

mobile-app/integration_test/learn/learn_landing.dart, mobile-app/pubspec.lock, mobile-app/pubspec.yaml
=> chore: remove http package

mobile-app/lib/ui/views/learn/challenge/templates/odin/odin_view.dart, mobile-app/lib/ui/views/learn/challenge/templates/python/python_view.dart, mobile-app/pubspec.lock, mobile-app/pubspec.yaml
=> fix: YT video fullscreen

mobile-app/analysis_options.yaml, mobile-app/pubspec.yaml
=> chore: organize imports

.lintstagedrc.json, mobile-app/ios/Podfile.lock, mobile-app/lib/app/app.dart, mobile-app/lib/app/app.locator.dart, mobile-app/lib/main.dart, mobile-app/lib/service/firebase/remote_config_service.dart, mobile-app/lib/utils/upgrade_controller.dart, mobile-app/pubspec.lock, mobile-app/pubspec.yaml
Checklist:
With Firebase Remote Config, we can use feature flags to enable features in the app slowly. Currently it has been setup to track the min app version for showing the upgrade app alert so that we can be sure that users will be in the latest update whenever we release breaking changes or open new certifications.
=> feat: integrate Firebase Remote Config

mobile-app/lib/service/firebase/remote_config_service.dart, mobile-app/pubspec.yaml
=> release(app): v4.2.0+40200

mobile-app/lib/ui/views/learn/challenge/templates/odin/odin_view.dart, mobile-app/lib/ui/views/learn/challenge/templates/python/python_view.dart, mobile-app/pubspec.lock, mobile-app/pubspec.yaml
This reverts commit fffc6d88097ff2037a95903b6a75c7b376438ccc.
Checklist:
=> Revert "fix: YT video fullscreen (#1256)"

mobile-app/lib/service/firebase/remote_config_service.dart, mobile-app/pubspec.yaml
=> release(app): v4.2.1+40201

mobile-app/lib/service/firebase/remote_config_service.dart, mobile-app/pubspec.yaml
=> release(app): v4.2.2+40202

mobile-app/lib/service/firebase/remote_config_service.dart, mobile-app/pubspec.yaml
=> release(app): v4.2.3+40203

.github/workflows/flutter-ci.yml, .github/workflows/flutter-deploy.yml, .github/workflows/mobile-curriculum-e2e.yml, codemagic.yaml, mobile-app/ios/Podfile.lock, mobile-app/lib/ui/theme/fcc_theme.dart, mobile-app/lib/ui/views/code_radio/code_radio_view.dart, mobile-app/lib/ui/views/login/native_login_view.dart, mobile-app/lib/ui/views/profile/profile_view.dart, mobile-app/lib/ui/widgets/podcast_widgets/podcast_tilte_widget.dart, mobile-app/pubspec.lock, mobile-app/pubspec.yaml
=> chore: flutter v3.22

mobile-app/lib/models/learn/challenge_model.dart
Checklist:
Ref: https://github.com/freeCodeCamp/freeCodeCamp/pull/55928
=> fix: question type

mobile-app/lib/service/firebase/remote_config_service.dart, mobile-app/pubspec.yaml
=> release(app): v4.3.0+40300

.github/workflows/flutter-ci.yml, .github/workflows/flutter-deploy.yml, .github/workflows/mobile-curriculum-e2e.yml, codemagic.yaml, mobile-app/android/app/build.gradle, mobile-app/android/settings.gradle, mobile-app/ios/Podfile, mobile-app/ios/Podfile.lock, mobile-app/ios/Runner/AppDelegate.swift, mobile-app/lib/models/learn/challenge_model.dart, mobile-app/lib/ui/views/learn/challenge/challenge_view.dart, mobile-app/lib/ui/views/learn/challenge/templates/odin/odin_view.dart, mobile-app/lib/ui/views/learn/challenge/templates/python-project/python_project_view.dart, mobile-app/lib/ui/views/learn/challenge/templates/python/python_view.dart, mobile-app/lib/ui/views/settings/settings_viewmodel.dart, mobile-app/lib/ui/widgets/drawer_widget/drawer_web_buttton.dart, mobile-app/pubspec.lock, mobile-app/pubspec.yaml
=> feat: flutter 3.24

mobile-app/lib/ui/views/learn/test_runner.dart
=> fix: mocha version maybe?

mobile-app/lib/ui/views/learn/test_runner.dart
=> fix: disable browser extensions check in test runner

mobile-app/lib/service/firebase/remote_config_service.dart, mobile-app/pubspec.yaml
=> release(app): 5.0.0+50000

mobile-app/lib/ui/views/learn/widgets/dynamic_panel/panels/description/description_widget_view.dart, mobile-app/lib/ui/views/learn/widgets/dynamic_panel/panels/dynamic_panel.dart
=> refactor: improve layout and styling in description and dynamic panel widgets

mobile-app/lib/models/learn/curriculum_model.dart, mobile-app/lib/ui/views/learn/block/block_view.dart, mobile-app/lib/ui/views/learn/utils/learn_globals.dart
=> fix: enable step-based layout for b1 english

mobile-app/lib/service/firebase/remote_config_service.dart, mobile-app/pubspec.yaml
=> release(app): 5.0.1+50001

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
=> chore(github): add waiting triage label to issue templates

.gitignore
Checklist:
I tried building for Android and got a bunch of files created under `android/app/.cxx`. This seems to be new, and Flutter team recommends adding it to `.gitignore` (https://github.com/flutter/flutter/issues/163220#issuecomment-2659978902).
=> chore: add .cxx directory to gitignore

mobile-app/lib/models/learn/challenge_model.dart
=> fix: typo in challenge model

mobile-app/lib/ui/views/learn/test_runner.dart
Checklist:
Ref: https://github.com/freeCodeCamp/mobile/actions/runs/14302788300/job/40080073516
=> fix: provide editableContents for tests

package-lock.json, package.json
=> chore: remove shx as it's unused

mobile-app/lib/app/app.dart, mobile-app/lib/app/app.locator.dart, mobile-app/lib/main.dart, mobile-app/lib/service/news/api_service.dart, mobile-app/lib/ui/views/news/news-author/news_author_viewmodel.dart, mobile-app/lib/ui/views/news/news-feed/news_feed_viewmodel.dart, mobile-app/lib/ui/views/news/news-tutorial/news_tutorial_viewmodel.dart, mobile-app/lib/ui/widgets/tutorial_list_widget.dart
=> fix: rename NewsApiServive to NewsApiService

mobile-app/lib/service/firebase/remote_config_service.dart, mobile-app/pubspec.yaml
=> release(app): v5.0.2+50002

mobile-app/ios/Podfile.lock, mobile-app/lib/ui/views/news/html_handler/html_handler.dart, mobile-app/pubspec.lock, mobile-app/pubspec.yaml
=> chore: update flutter_html to v3 and update underline style

mobile-app/lib/ui/views/news/html_handler/html_handler.dart
=> fix: improve regex for code language detection in HTMLParser

mobile-app/lib/service/firebase/remote_config_service.dart, mobile-app/pubspec.yaml
=> release(app): v5.0.3+50003

mobile-app/lib/ui/views/learn/widgets/dynamic_panel/panels/pass/pass_widget_view.dart
=> fix: pass widget overflow error

mobile-app/lib/ui/views/learn/challenge/challenge_view.dart
=> fix: border between editor and bottom bar

.github/workflows/flutter-ci.yml, .github/workflows/flutter-deploy.yml, .github/workflows/mobile-curriculum-e2e.yml, codemagic.yaml, mobile-app/android/app/google-services.json, mobile-app/ios/Podfile.lock, mobile-app/ios/Runner.xcodeproj/project.pbxproj, mobile-app/ios/Runner/GoogleService-Info.plist, mobile-app/lib/firebase_options.dart, mobile-app/pubspec.lock, mobile-app/pubspec.yaml
=> feat: flutter 3.29

mobile-app/lib/ui/theme/fcc_theme.dart
Checklist:
This PR:
- Adds colors from the design system to FccTheme - The idea is we would reference these colors when styling the UI, rather than applying `Color()` directly. 
- I'll have separate PRs to replace those direct `Colors` usages.
- Closes #1408
=> chore: add design system colors

mobile-app/lib/ui/views/learn/challenge/templates/multiple_choice/multiple_choice_view.dart, mobile-app/lib/ui/views/learn/challenge/templates/multiple_choice/multiple_choice_viewmodel.dart
Checklist:
Closes #1419 and closes #1468
=> feat: add multiple choice feedback and answer tracking

mobile-app/lib/models/learn/curriculum_model.dart, mobile-app/lib/ui/views/learn/superblock/superblock_viewmodel.dart
Checklist:
This PR:
- Updates the `Block` and `SuperBlock` models to consume v2 data
- Unblocks #1458
- Is related to #1426
=> chore(model, viewmodel): use v2 superblock and block data

mobile-app/lib/ui/views/learn/widgets/audio/audio_player_view.dart
=> fix: jittery audio widget layout

mobile-app/lib/ui/views/learn/challenge/challenge_view.dart, mobile-app/lib/ui/views/learn/challenge/challenge_viewmodel.dart
=> feat: add 'Tab' symbol

mobile-app/lib/service/audio/audio_service.dart, mobile-app/lib/service/learn/learn_offline_service.dart, mobile-app/lib/service/learn/learn_service.dart, mobile-app/lib/service/locale_service.dart, mobile-app/lib/ui/views/code_radio/code_radio_viewmodel.dart, mobile-app/lib/ui/views/learn/block/block_viewmodel.dart, mobile-app/lib/ui/views/learn/challenge/challenge_viewmodel.dart, mobile-app/lib/ui/views/news/news-tutorial/news_tutorial_viewmodel.dart
Checklist:
`prefs.set*` and `prefs.remove()` are async operations, so they should be called with `await`.
=> fix: wait for async preferences setting

mobile-app/lib/ui/views/podcast/episode/episode_view.dart, mobile-app/lib/ui/views/podcast/episode/episode_viewmodel.dart
=> feat(viewmodel): prevent loading episode if already playing another episode and update play/pause logic

mobile-app/lib/ui/views/learn/landing/landing_viewmodel.dart, mobile-app/lib/ui/views/learn/superblock/superblock_view.dart, mobile-app/lib/ui/views/learn/superblock/superblock_viewmodel.dart
- **fix: replace getSuperBlocks with requestSuperBlocks in LearnLandingViewModel**
- **fix: refactor streamline data fetching**
Checklist:
Closes #1496
=> fix: prevent calling superblock list and superblock on challenge init 

mobile-app/integration_test/test_runner/curriculum_tests.dart, mobile-app/lib/service/learn/learn_file_service.dart, mobile-app/lib/ui/views/learn/test_runner.dart, mobile-app/test/unit/learn_file_controller_test.dart
Checklist:
Also, removed an unnecessary check for the returned file.
=> fix: update getCurrentEditedFileFromCache to return ChallengeFile and adjust related tests

mobile-app/lib/ui/views/learn/block/block_template_viewmodel.dart, mobile-app/lib/ui/views/learn/block/templates/grid/grid_view.dart, mobile-app/lib/ui/views/learn/block/templates/link/link_view.dart, mobile-app/lib/ui/views/learn/block/templates/list/list_view.dart
| Grid | List | Link |
|--------|--------|--------|
| <img width="338" alt="image" src="https://github.com/user-attachments/assets/a99b2c6d-fe80-4046-8ec3-f3100e6fa860" /> | <img width="338" alt="image" src="https://github.com/user-attachments/assets/02e60d1e-6f73-489d-80fa-42a748faa9fa" /> | <img width="338" alt="image" src="https://github.com/user-attachments/assets/df6190e7-632b-4783-860f-4b5e1f7d8b9c" /> |
=> feat: enhance challenge completion indicators in grid and list views

mobile-app/lib/ui/views/learn/challenge/templates/multiple_choice/multiple_choice_view.dart, mobile-app/lib/ui/views/learn/challenge/templates/multiple_choice/multiple_choice_viewmodel.dart, mobile-app/lib/ui/views/learn/challenge/templates/review/review_view.dart, mobile-app/lib/ui/views/learn/challenge/templates/review/review_viewmodel.dart, mobile-app/lib/ui/views/learn/challenge/templates/template_view.dart, mobile-app/lib/ui/views/learn/widgets/assignment_widget.dart
=> feat(view, viewmodel): add review page

mobile-app/integration_test/test_runner/test_runner_view.dart, mobile-app/lib/ui/views/learn/challenge/challenge_view.dart
=> fix(test_runner): update initial URL request to point to index.js

mobile-app/integration_test/test_runner/test_runner_view.dart, mobile-app/lib/ui/views/learn/challenge/challenge_view.dart
I don't hear anything while the tests are running, so I think this approach is okay. If it proves not to be, we should be able to solve it with mocks.
Checklist:
=> fix: allow audio to play in tests

mobile-app/integration_test/learn/learn_landing.dart, mobile-app/lib/service/learn/learn_service.dart
Checklist:
This PR:
- Updates the last file that uses v1 data
- Closes #1426
=> chore: update learn_landing.dart to use v2 data

mobile-app/lib/ui/views/learn/challenge/challenge_view.dart, mobile-app/lib/ui/views/learn/challenge/challenge_viewmodel.dart, mobile-app/lib/ui/views/learn/widgets/dynamic_panel/panels/hint/hint_widget_view.dart
Checklist:
Closes https://github.com/freeCodeCamp/mobile/issues/1455
=> feat: put dynamic panel in end drawer free up screen space

mobile-app/lib/ui/views/learn/challenge/templates/multiple_choice/multiple_choice_viewmodel.dart, mobile-app/lib/ui/views/learn/challenge/templates/python/python_viewmodel.dart
Checklist:
Updates the logic for handling MCQ selection to prevent unnecessary UI rebuilds.
=> fix(viewmodel): unnecessary validation status and error message reset

.github/workflows/flutter-ci.yml, .github/workflows/flutter-deploy.yml, .github/workflows/mobile-curriculum-e2e.yml, codemagic.yaml, mobile-app/ios/Flutter/ephemeral/flutter_lldb_helper.py, mobile-app/ios/Flutter/ephemeral/flutter_lldbinit, mobile-app/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, mobile-app/l10n.yaml, mobile-app/lib/extensions/i18n_extension.dart, mobile-app/lib/l10n/app_localizations.dart, mobile-app/lib/l10n/app_localizations_en.dart, mobile-app/lib/l10n/app_localizations_es.dart, mobile-app/lib/l10n/app_localizations_pt.dart, mobile-app/lib/main.dart, mobile-app/pubspec.lock
=> feat: flutter 3.32

mobile-app/lib/ui/views/profile/profile_view.dart
=> refactor: ProfileView for improved layout and readability

mobile-app/lib/enums/ext_type.dart
Checklist:
Adds `py` to the `Ext` enum.
<details>
| --- | --- |
| <img width="398" alt="Screenshot 2025-06-27 at 17 46 48" src="https://github.com/user-attachments/assets/42e7be3a-7da6-4467-b4ab-2603248d582d" /> | <img width="392" alt="Screenshot 2025-06-27 at 17 45 21" src="https://github.com/user-attachments/assets/ffa9eda2-cc6b-4fd8-830c-96a3e7889423" /> |
</details>
=> feat: add py to file extension list

mobile-app/lib/ui/views/learn/widgets/hint/hint_widget_view.dart
=> chore(view): remove unused preview  from Hint Widget

mobile-app/lib/service/learn/learn_file_service.dart, mobile-app/lib/ui/views/learn/challenge/challenge_view.dart, mobile-app/lib/ui/views/learn/challenge/challenge_viewmodel.dart, mobile-app/lib/ui/views/learn/test_runner.dart, mobile-app/lib/ui/views/learn/widgets/console/console_view.dart, mobile-app/lib/ui/views/learn/widgets/console/console_viewmodel.dart
=> feat: console messages UI

mobile-app/lib/service/learn/learn_file_service.dart, mobile-app/lib/ui/views/learn/challenge/challenge_viewmodel.dart, mobile-app/lib/ui/views/learn/test_runner.dart, mobile-app/test/unit/learn_file_controller_test.dart
Checklist:
#1590 scared me so I'm adding some more unit tests for peace of mind.
The tests are for the following functions:
- `jsFileIsLinked`
- `changeActiveFileLinks`
- `parseCssDocumentsAsStyleTags`
- `parseJsDocumentsAsScriptTags`
=> test: add more tests for learn file service

.github/workflows/mobile-curriculum-e2e.yml
Checklist:
The test was failing due to the old version of chrome in the older Android version,.
I've also moved the versions into matrix to make it easier to update them from one place.
=> fix: android failing e2e test

mobile-app/lib/ui/views/learn/widgets/pass/pass_widget_view.dart
Checklist:
This PR:
- Is needed for #1635 (I decided to keep this change in a separate PR as it's not really related to daily challenges)
- Closes #1637
<details>
<summary>Screen recording</summary>
https://github.com/user-attachments/assets/6e3aa555-544f-4c33-a1d4-7f0c62e6fc41
</details>
=> fix(view): ensure end drawer closes before navigation

mobile-app/lib/ui/views/learn/challenge/challenge_viewmodel.dart
Checklist:
<details>
<summary>Details</summary>
|--------|--------|
| <img width="1179" height="2556" alt="image" src="https://github.com/user-attachments/assets/bebf896c-e8f8-45c6-9cee-88c5bb5a3def" /> | <img width="1179" height="2556" alt="image" src="https://github.com/user-attachments/assets/45b4223d-4baa-4471-8d3f-ef5b7fd593c6" /> |
</details>
=> fix: replace expected and actual placeholders in hint text

mobile-app/lib/ui/views/news/html_handler/html_handler.dart
=> feat: copy highlighted text to clipboard on tap
